export interface Card {
  id: number;
  category: string;
  subCategory: string;
  title: string;
  text: string;
}

export const SAMPLE_CARDS: Card[] = [
  {
    id: 1,
    category: "character",
    subCategory: "role",
    title: "ท่านประธาน VIP",
    text: "ห้ามรินเหล้าหรือหยิบของกินเอง ต้องชี้นิ้วสั่งเพื่อนข้าง ๆ ให้ทำให้เท่านั้น ถ้าทำเองโดน!",
  },
  {
    id: 2,
    category: "character",
    subCategory: "role",
    title: "เด็กอินเตอร์",
    text: "ห้ามพูดภาษาไทย! Speak English only (งู ๆ ปลา ๆ ก็ได้) หลุดไทยเมื่อไหร่ โดน!",
  },
  {
    id: 3,
    category: "character",
    subCategory: "role",
    title: "ครับพี่ดีครับท่าน",
    text: "ห้ามปฏิเสธ! ใครถามอะไรต้องตอบว่า 'ใช่ครับพี่ / ดีครับผม / เหมาะสมครับท่าน' เท่านั้น หลุดคำอื่นโดน!",
  },
  {
    id: 4,
    category: "character",
    subCategory: "role",
    title: "คนหน้าตึง",
    text: "ห้ามหัวเราะ ห้ามยิ้ม ต้องทำหน้าตึงตลอด ถ้าใครทำให้คุณหลุดขำได้ คุณโดน!",
  },
  {
    id: 5,
    category: "character",
    subCategory: "role",
    title: "น้องแมวเมี๊ยว",
    text: "ทุกประโยคที่พูดจบ ต้องลงท้ายด้วยเสียง 'เมี๊ยว~' ห้ามลืม! ถ้าลืมพูดโดน!",
  },
  {
    id: 6,
    category: "character",
    subCategory: "role",
    title: "เจ้าหนูจำไม",
    text: "ห้ามพูดประโยคบอกเล่า ต้องสื่อสารเป็นคำถามเท่านั้น ถ้าเผลอพูดประโยคปกติโดน!",
  },
  {
    id: 7,
    category: "character",
    subCategory: "role",
    title: "เงาเสียง",
    text: "ใครพูดประโยคสุดท้ายจบ คุณต้องพูดทวน 3 คำสุดท้ายซ้ำอีกที ถ้าไม่ทวนตามโดน!",
  },
  {
    id: 8,
    category: "character",
    subCategory: "role",
    title: "ฝาแฝด",
    text: "เลือกเพื่อน 1 คน คุณต้องทำท่าทางตามเพื่อนคนนั้นทุกอย่าง ถ้าทำตามไม่ทันโดน!",
  },
  {
    id: 9,
    category: "character",
    subCategory: "role",
    title: "ห้ามเรียกชื่อ",
    text: "ห้ามเรียกชื่อจริงหรือชื่อเล่นเพื่อน ใช้คำสรรพนามตลก ๆ แทนเท่านั้น ใครเผลอเรียกชื่อเพื่อนโดน!",
  },
  {
    id: 10,
    category: "character",
    subCategory: "role",
    title: "กุลสตรีไทย",
    text: "ห้ามพูดคำหยาบเด็ดขาด ต้องพูดจาสุภาพเรียบร้อยแบบนางงาม ถ้าหลุดคำหยาบโดน!",
  },
  {
    id: 11,
    category: "character",
    subCategory: "role",
    title: "งดใช้มือถือ",
    text: "ห้ามแตะมือถือเด็ดขาด ใครไลน์มาห้ามตอบ ใครโทรมาห้ามรับ ถ้าเผลอหยิบมาดูโดน!",
  },
  {
    id: 12,
    category: "character",
    subCategory: "role",
    title: "พนักงานยืนหนึ่ง",
    text: "ห้ามนั่งเก้าอี้ ต้องยืนเล่นหรือนั่งพื้นเท่านั้น ถ้าก้นแตะเก้าอี้โดน!",
  },
  {
    id: 13,
    category: "character",
    subCategory: "role",
    title: "เด็กดริ๊งค์ประจำวง",
    text: "ถ้าแก้วใครพร่องเกินครึ่ง คุณต้องเติมให้ทันที ห้ามให้แก้วว่าง ถ้าเพื่อนประท้วงว่าแก้วแห้งคุณโดน!",
  },
  {
    id: 14,
    category: "character",
    subCategory: "role",
    title: "ดาวติ๊กต็อก",
    text: "ก่อนดื่มทุกครั้ง ต้องทำท่า Boomerang ชนแก้ว แล้วพูดว่า 'Cheers!' ถ้าลืมทำท่าโดน!",
  },
  {
    id: 15,
    category: "character",
    subCategory: "role",
    title: "สายลับ 007",
    text: "ห้ามสบตาใครตรง ๆ เวลาคุยต้องมองหูหรือเพดานเท่านั้น ถ้าเผลอสบตาใครโดน!",
  },

  {
    id: 16,
    category: "question",
    subCategory: "deep",
    title: "เปิดอกคุย",
    text: "ถ้าพรุ่งนี้โลกแตก อยากขอโทษใครในวงนี้มากที่สุดและเรื่องอะไร? ถ้าไม่กล้าตอบโดน!",
  },
  {
    id: 17,
    category: "question",
    subCategory: "exposed",
    title: "ขอดูหน่อย",
    text: "เปิดรูปที่ 5 ในอัลบั้มมือถือให้ทุกคนดู ห้ามข้ามห้ามเปลี่ยน ถ้าไม่เปิดโดน!",
  },
  {
    id: 18,
    category: "question",
    subCategory: "roast",
    title: "ใครบูดสุด",
    text: "ใครในวงนี้แต่งตัวไม่รอดที่สุดวันนี้? ชี้เลย ถ้าไม่กล้าชี้คุณโดนเอง!",
  },
  {
    id: 19,
    category: "question",
    subCategory: "truth",
    title: "ความลับนางฟ้า",
    text: "เคยโกหกเพื่อนในวงนี้แล้วยังไม่ได้เฉลยไหม? เล่ามาเดี๋ยวนี้ ถ้าไม่เล่าโดน!",
  },
  {
    id: 20,
    category: "question",
    subCategory: "ความประทับใจ",
    title: "แรกพบสบตา",
    text: "บอกความประทับใจแรกที่มีต่อคนทางขวามือแบบตรง ๆ ถ้าพูดไม่จริงใจเพื่อนโหวตให้โดน!",
  },
  {
    id: 21,
    category: "question",
    subCategory: "dating",
    title: "เรื่องรัก ๆ",
    text: "สเปคที่ชอบ vs ความเป็นจริงที่เจอ ต่างกันยังไง? ถ้าไม่ตอบโดน!",
  },
  {
    id: 22,
    category: "question",
    subCategory: "ghost",
    title: "โดนเทหรือเทเขา",
    text: "เคยเทใครหรือโดนใครเทแบบงงที่สุดในชีวิต? เล่ามา ถ้าไม่เล่าโดน!",
  },
  {
    id: 23,
    category: "question",
    subCategory: "social",
    title: "เลือกมาหนึ่ง",
    text: "ถ้าต้อง Unfriend เพื่อนในวงนี้ 1 คน จะเลือกใคร เพราะอะไร? ถ้าไม่เลือกคุณโดน!",
  },
  {
    id: 24,
    category: "question",
    subCategory: "cringe",
    title: "วีรกรรมสุดรั่ว",
    text: "เรื่องน่าอายที่สุดที่เคยทำตอนเมาคืออะไร? เล่ามาให้เห็นภาพ ถ้าไม่เล่าโดน!",
  },
  {
    id: 25,
    category: "question",
    subCategory: "rich",
    title: "มหาเศรษฐี",
    text: "ถ้าถูกหวยรางวัลที่ 1 จะพาเพื่อนในวงไปเลี้ยง หรือหนีไปคนเดียว? ตอบมา ถ้าเพื่อนไม่เชื่อโดน!",
  },

  {
    id: 26,
    category: "minigame",
    subCategory: "category",
    title: "ร้านสะดวกซื้อ",
    text: "ไล่ตอบชื่อของที่มีขายใน 7-11 ทีละคน ใครคิดนานหรือตอบซ้ำโดน!",
  },
  {
    id: 27,
    category: "minigame",
    subCategory: "category",
    title: "ติ่งวงไหน",
    text: "ไล่ตอบชื่อศิลปิน T-POP หรือ K-POP ทีละคน ใครนึกไม่ออกโดน!",
  },
  {
    id: 28,
    category: "minigame",
    subCategory: "category",
    title: "สารพัดไข่",
    text: "ไล่ตอบเมนูที่มีไข่เป็นส่วนประกอบ ห้ามซ้ำ ใครตอบช้าโดน!",
  },
  {
    id: 29,
    category: "minigame",
    subCategory: "category",
    title: "สระอาพาเพลิน",
    text: "พูดคำ 2 พยางค์ที่มีสระอา (เช่น มาหา, ลาลา) ใครพูดคำไม่มีความหมายหรือซ้ำโดน!",
  },
  {
    id: 30,
    category: "minigame",
    subCategory: "category",
    title: "คนรักรถ",
    text: "ไล่ตอบชื่อยี่ห้อรถยนต์ทีละคน ห้ามซ้ำ ใครตอบคนสุดท้ายไม่ได้โดน!",
  },

  {
    id: 31,
    category: "minigame",
    subCategory: "reaction",
    title: "รูปปั้นนิ่ง",
    text: "ทุกคนต้องหยุดนิ่ง ห้ามกระพริบตา ห้ามยิ้ม ใครขยับก่อนคนแรกโดน!",
  },
  {
    id: 32,
    category: "minigame",
    subCategory: "reaction",
    title: "เสียงสูงปรี๊ด",
    text: "ร้องเพลงท่อนฮุคด้วยเสียงแหลมที่สุด ใครเสียงหลงหรือทำไม่ได้โดน!",
  },
  {
    id: 33,
    category: "minigame",
    subCategory: "reaction",
    title: "นับเลขพร้อมกัน",
    text: "นับ 1-10 พร้อมกันโดยไม่นัดหมาย ใครพูดเลขชนกันโดน!",
  },
  {
    id: 34,
    category: "minigame",
    subCategory: "reaction",
    title: "ตั้งหมวด",
    text: "คนจั่วตั้งหมวดอะไรก็ได้ แล้วไล่ตอบทีละคน ใครตอบไม่ได้คนแรกโดน!",
  },
  {
    id: 35,
    category: "minigame",
    subCategory: "reaction",
    title: "นิ้วพิฆาต",
    text: "เล่นเกม 'ไม่เคยทำ...' ใครเอาลงครบ 3 นิ้วก่อนคนแรกโดน!",
  },
  {
    id: 36,
    category: "minigame",
    subCategory: "reaction",
    title: "ตาจ้องตา",
    text: "นับ 1-3 แล้วมองหน้ากัน ถ้าสบตากันเองจัง ๆ โดนทั้งคู่!",
  },
  {
    id: 37,
    category: "minigame",
    subCategory: "challenge",
    title: "จิตรกรหลังเพื่อน",
    text: "วาดรูปบนหลังคนขวาให้เขาทาย ถ้าเขาทายไม่ถูก คุณโดน!",
  },
  {
    id: 38,
    category: "minigame",
    subCategory: "challenge",
    title: "ต่อกลอน",
    text: "พูดคำคล้องจองต่อกัน ใครคิดคำต่อไปไม่ออกภายใน 3 วิ โดน!",
  },
  {
    id: 39,
    category: "minigame",
    subCategory: "challenge",
    title: "แบตใครน้อย",
    text: "โชว์เปอร์เซ็นต์แบตมือถือ ใครแบตน้อยที่สุดในวง โดน!",
  },
  {
    id: 40,
    category: "minigame",
    subCategory: "challenge",
    title: "ชื่อใครสั้น",
    text: "เช็คชื่อเล่นกัน ใครชื่อเล่นยาวที่สุดในวง โดน!",
  },

  {
    id: 41,
    category: "normal",
    subCategory: "vote",
    title: "โหวตคนเจ้าชู้",
    text: "นับ 1-3 แล้วชี้คนที่มีแววเจ้าชู้เงียบที่สุด ใครโดนชี้มากสุดโดน!",
  },
  {
    id: 42,
    category: "normal",
    subCategory: "vote",
    title: "โหวตขึ้นคาน",
    text: "โหวตคนที่น่าจะครองโสดนานที่สุดในกลุ่ม คนโดนโหวตโดน!",
  },
  {
    id: 43,
    category: "normal",
    subCategory: "vote",
    title: "โหวตคนรั่ว",
    text: "ใครเมาแล้วรั่วหรือเปลี่ยนไปเป็นคนละคนมากที่สุด คนนั้นโดน!",
  },
  {
    id: 44,
    category: "normal",
    subCategory: "vote",
    title: "โหวตคนรวย",
    text: "ใครดูมีโหงวเฮ้งจะรวยทางลัด (หรือทำเว็บ...) ที่สุด คนนั้นโดน!",
  },
  {
    id: 45,
    category: "normal",
    subCategory: "vote",
    title: "โหวตคนโชคดี",
    text: "โหวตคนที่คุณอยากให้มีความสุขที่สุดปีนี้ คนนั้นรอด (ที่เหลือโดนจิบฉลอง)!",
  },

  {
    id: 46,
    category: "normal",
    subCategory: "break",
    title: "พักยก",
    text: "พักเบรก 5 นาที ให้ไปเข้าห้องน้ำหรือเช็คไลน์ได้ ใครกลับมาไม่ทันโดน!",
  },
  {
    id: 47,
    category: "normal",
    subCategory: "break",
    title: "บัตรข้ามด่าน",
    text: "เก็บไพ่นี้ไว้ใช้ปัดบทลงโทษให้เพื่อนคนอื่นได้ 1 ครั้ง ถ้าไม่ใช้จนจบเกมโดน!",
  },
  {
    id: 48,
    category: "normal",
    subCategory: "break",
    title: "ชนแก้วสามัคคี",
    text: "ทุกคนชนแก้วและจิบพร้อมกันเพื่อมิตรภาพ ใครไม่จิบโดน!",
  },

  {
    id: 49,
    category: "normal",
    subCategory: "action",
    title: "รับไปเต็ม ๆ",
    text: "ผู้จั่วรับบทลงโทษไปเลย 1 ชุด ห้ามขัดขืน!",
  },
  {
    id: 50,
    category: "normal",
    subCategory: "action",
    title: "หาเพื่อนร่วมชะตา",
    text: "ผู้จั่วรับบทลงโทษ 1 ชุด และเลือกเพื่อนมาโดนด้วยกันอีก 1 คน!",
  },
  {
    id: 51,
    category: "normal",
    subCategory: "action",
    title: "ประกาศให้โลกรูู้",
    text: "ถ่ายรูปกลุ่มลง Story พร้อมแคปชั่น 'รักพวกมึงนะ' ถ้าไม่ลงโดน!",
  },
  {
    id: 52,
    category: "normal",
    subCategory: "action",
    title: "วัดดวงเป่ายิ้งฉุบ",
    text: "เป่ายิ้งฉุบกับเพื่อนซ้ายมือ ใครแพ้โดน!",
  },
  {
    id: 53,
    category: "normal",
    subCategory: "action",
    title: "ตามสั่งคนขวา",
    text: "คนขวาสั่งให้คุณทำอะไรก็ได้ 1 อย่าง ถ้าไม่ทำตามโดนหนักกว่าเดิม!",
  },
  {
    id: 54,
    category: "normal",
    subCategory: "action",
    title: "สายด่วนคิดถึง",
    text: "โทรหาเพื่อนที่ไม่ได้มา แล้วบอกว่า 'คิดถึงจัง' ถ้าเขาด่ากลับหรือวางสายคุณโดน!",
  },
  {
    id: 55,
    category: "normal",
    subCategory: "action",
    title: "ย้ายรัง",
    text: "ทุกคนต้องเปลี่ยนที่นั่งใหม่หมด ใครนั่งที่เดิมหรือช้าที่สุดโดน!",
  },
  {
    id: 56,
    category: "normal",
    subCategory: "action",
    title: "ป้อนด้วยรัก",
    text: "ป้อนขนมหรือน้ำให้เพื่อนซ้ายมือ 1 คำ ถ้าทำหกคุณโดนเอง!",
  },
  {
    id: 57,
    category: "normal",
    subCategory: "action",
    title: "โชว์สเต็ป",
    text: "เต้นหรือร้องเพลงท่อนฮุค 1 เพลง ถ้าเพื่อนไม่ตบมือให้คุณโดน!",
  },
  {
    id: 58,
    category: "normal",
    subCategory: "action",
    title: "ดีเจอาสา",
    text: "เปิดเพลงที่ชอบให้เพื่อนฟังจนจบ ห้ามกดข้าม ถ้ามีคนกดข้ามคุณโดน!",
  },
  {
    id: 59,
    category: "normal",
    subCategory: "action",
    title: "ไหว้สวยรวยกระเช้า",
    text: "เดินไหว้สวย ๆ รอบวง พร้อมพูดว่า 'ขออภัยที่ขัดจังหวะ' ถ้าทำไม่สวยโดน!",
  },
  {
    id: 60,
    category: "normal",
    subCategory: "action",
    title: "จ้องตาพาเพลิน",
    text: "จ้องตากับคนตรงข้าม 10 วินาที ใครหลบตาหรือขำก่อนโดน!",
  },
  {
    id: 61,
    category: "normal",
    subCategory: "action",
    title: "ดาวตลก",
    text: "เล่าเรื่องตลก 1 เรื่อง ถ้าไม่มีใครขำเลยแม้แต่คนเดียว คุณโดน!",
  },
  {
    id: 62,
    category: "normal",
    subCategory: "action",
    title: "รูปเผลอต้องมา",
    text: "เซลฟี่หน้าเผลอ (หน้าตลก) ส่งเข้าไลน์กลุ่มทันที ถ้าไม่ส่งโดน!",
  },
  {
    id: 63,
    category: "normal",
    subCategory: "action",
    title: "สายสุขภาพ",
    text: "ดื่มน้ำเปล่า 1 แก้วเต็ม ๆ ต่อหน้าเพื่อน ถ้าดื่มไม่หมดโดน!",
  },
  {
    id: 64,
    category: "normal",
    subCategory: "action",
    title: "คู่หูดูโอ้",
    text: "จับคู่ Buddy กับคนข้างขวา ใครคนใดคนหนึ่งโดน อีกคนต้องโดนด้วยจนจบเกม!",
  },
  {
    id: 65,
    category: "normal",
    subCategory: "action",
    title: "นักแสดงยอดเยี่ยม",
    text: "แกล้งทำเป็นเมาพูดไม่รู้เรื่องเป็นเวลา 1 นาที ถ้าหลุดขำก่อนโดน!",
  },
  {
    id: 66,
    category: "normal",
    subCategory: "action",
    title: "นักรีวิว",
    text: "รีวิวข้อเสียของเพื่อนข้าง ๆ เหมือนรีวิวสินค้า ถ้าพูดไม่โดนใจเพื่อนโดน!",
  },
  {
    id: 67,
    category: "normal",
    subCategory: "action",
    title: "ท่าไม้ตายเซ็กซี่",
    text: "ทำท่าที่คิดว่าเซ็กซี่ที่สุด 1 ท่า ถ้าเพื่อนไม่โห่ร้องคุณโดน!",
  },
  {
    id: 68,
    category: "normal",
    subCategory: "action",
    title: "อวยตัวเอง",
    text: "บอกข้อดีของตัวเองมา 3 ข้อ ห้ามซ้ำกับที่เคยพูด ถ้าคิดนานโดน!",
  },

  {
    id: 69,
    category: "normal",
    subCategory: "position",
    title: "ซ้ายซวยแล้ว",
    text: "คนทางซ้ายมือของผู้จั่ว รับบทลงโทษไป 1 ชุด!",
  },
  {
    id: 70,
    category: "normal",
    subCategory: "position",
    title: "ขวาขี้แตก",
    text: "คนทางขวามือของผู้จั่ว รับบทลงโทษไป 1 ชุด!",
  },
  {
    id: 71,
    category: "normal",
    subCategory: "position",
    title: "ตรงข้ามโดน",
    text: "คนนั่งตรงข้ามกับผู้จั่ว รับบทลงโทษไป 1 ชุด!",
  },
  {
    id: 72,
    category: "normal",
    subCategory: "position",
    title: "ซ้ายคนที่สอง",
    text: "นับจากซ้ายไปคนที่ 2 คนนั้นโดน!",
  },
  {
    id: 73,
    category: "normal",
    subCategory: "position",
    title: "ขวาคนที่สอง",
    text: "นับจากขวาไปคนที่ 2 คนนั้นโดน!",
  },
  {
    id: 74,
    category: "normal",
    subCategory: "position",
    title: "โดนแพ็คสาม",
    text: "ผู้จั่วและคนซ้าย-ขวา รับบทลงโทษพร้อมกันสามคน!",
  },
  {
    id: 75,
    category: "normal",
    subCategory: "position",
    title: "รอดคนเดียว",
    text: "ทุกคนในวงโดนหมด ยกเว้นผู้จั่วคนเดียวที่รอด!",
  },
  {
    id: 76,
    category: "normal",
    subCategory: "position",
    title: "ชี้ซ้ายใครโดน",
    text: "หลับตาแล้วชี้ไปทางซ้าย นิ้วหยุดที่ใครคนนั้นโดน!",
  },
  {
    id: 77,
    category: "normal",
    subCategory: "position",
    title: "ชี้ขวาใครโดน",
    text: "หลับตาแล้วชี้ไปทางขวา นิ้วหยุดที่ใครคนนั้นโดน!",
  },
  {
    id: 78,
    category: "normal",
    subCategory: "position",
    title: "เฝ้าประตู",
    text: "คนนั่งใกล้ประตู (หรือทางออก) ที่สุดตอนนี้ โดน!",
  },

  {
    id: 79,
    category: "normal",
    subCategory: "attribute",
    title: "คนใส่แว่น",
    text: "ใครใส่แว่นอยู่ตอนนี้ (รวมแว่นสายตา/แฟชั่น) โดน!",
  },
  {
    id: 80,
    category: "normal",
    subCategory: "attribute",
    title: "ขาวดำคลาสสิก",
    text: "ใครใส่เสื้อสีขาวหรือสีดำอยู่ตอนนี้ โดน!",
  },
  {
    id: 81,
    category: "normal",
    subCategory: "attribute",
    title: "เสาไฟฟ้า",
    text: "ใครตัวสูงที่สุดในวงตอนนี้ โดน!",
  },
  {
    id: 82,
    category: "normal",
    subCategory: "attribute",
    title: "ไซส์พกพา",
    text: "ใครตัวเล็ก (เตี้ย) ที่สุดในวงตอนนี้ โดน!",
  },
  {
    id: 83,
    category: "normal",
    subCategory: "attribute",
    title: "ผมยาวสลวย",
    text: "ใครผมยาวเกินบ่าลงไป โดน!",
  },
  {
    id: 84,
    category: "normal",
    subCategory: "attribute",
    title: "ผมสั้นทันใจ",
    text: "ใครผมสั้น (ไม่ถึงบ่า) โดน!",
  },
  {
    id: 85,
    category: "normal",
    subCategory: "attribute",
    title: "เดือนมีคม",
    text: "ใครเกิดเดือนที่ลงท้ายด้วยคำว่า 'คม' โดน!",
  },
  {
    id: 86,
    category: "normal",
    subCategory: "attribute",
    title: "เดือนมียน",
    text: "ใครเกิดเดือนที่ลงท้ายด้วยคำว่า 'ยน' โดน!",
  },
  {
    id: 87,
    category: "normal",
    subCategory: "attribute",
    title: "อาถรรพ์กุมภา",
    text: "ใครเกิดเดือนกุมภาพันธ์ โดน! (ถ้าไม่มีใครเกิดเดือนนี้ ผู้จั่วรับไปเอง)",
  },
  {
    id: 88,
    category: "normal",
    subCategory: "attribute",
    title: "ชื่อพยางค์เดียว",
    text: "ใครชื่อเล่นมีพยางค์เดียว โดน!",
  },
  {
    id: 89,
    category: "normal",
    subCategory: "attribute",
    title: "อักษร น.",
    text: "ใครชื่อจริงมีตัวอักษร 'น' อยู่ในชื่อ โดน!",
  },
  {
    id: 90,
    category: "normal",
    subCategory: "attribute",
    title: "พี่ใหญ่ใจดี",
    text: "ใครอายุมากที่สุดในวงตอนนี้ โดน!",
  },
  {
    id: 91,
    category: "normal",
    subCategory: "attribute",
    title: "น้องเล็กของวง",
    text: "ใครอายุน้อยที่สุดในวงตอนนี้ โดน!",
  },
  {
    id: 92,
    category: "normal",
    subCategory: "attribute",
    title: "เท้าเปล่า",
    text: "ใครไม่ใส่ถุงเท้าอยู่ตอนนี้ โดน!",
  },
  {
    id: 93,
    category: "normal",
    subCategory: "attribute",
    title: "เวลามีค่า",
    text: "ใครใส่นาฬิกาข้อมืออยู่ตอนนี้ โดน!",
  },

  {
    id: 94,
    category: "normal",
    subCategory: "status",
    title: "โสดโปรดจีบ",
    text: "ใครสถานะโสด (ไม่มีแฟน/คนคุย) โดน!",
  },
  {
    id: 95,
    category: "normal",
    subCategory: "status",
    title: "คนมีคู่",
    text: "ใครมีแฟนหรือมีคนคุยอยู่ตอนนี้ โดน!",
  },
  {
    id: 96,
    category: "normal",
    subCategory: "status",
    title: "ติดมือถือ",
    text: "ใครไถมือถือบ่อยที่สุดใน 10 นาทีที่ผ่านมา เพื่อนโหวตมา คนนั้นโดน!",
  },
  {
    id: 97,
    category: "normal",
    subCategory: "status",
    title: "หน้าแดงเป็นลูกตำลึง",
    text: "ใครหน้าแดงที่สุดในวงตอนนี้ โดน!",
  },
  {
    id: 98,
    category: "normal",
    subCategory: "status",
    title: "เน็ตไอดอล",
    text: "ใครมียอดผู้ติดตาม IG เยอะที่สุดในวง โดน!",
  },
  {
    id: 99,
    category: "normal",
    subCategory: "status",
    title: "สังคมไร้เงินสด",
    text: "ใครพกเงินสดติดตัวน้อยที่สุดตอนนี้ โดน!",
  },
  {
    id: 100,
    category: "normal",
    subCategory: "status",
    title: "แจ็คพอตแตก",
    text: "ผู้จั่วเลือกใครก็ได้ 1 คนให้รับบทลงโทษแทน หรือจะรับเองเพื่อโชว์แมนก็ได้!",
  },
];
