export interface Card {
  id: number;
  category: string;
  subCategory: string;
  title: string;
  text: string;
}

export const SAMPLE_CARDS: Card[] = [
  {
    id: 1,
    category: "character",
    subCategory: "role",
    title: "THE VIP",
    text: "ห้ามรินเหล้าหรือหยิบของกินเอง ต้องชี้นิ้วสั่งเพื่อนข้าง ๆ ให้ทำให้เท่านั้น",
  },
  {
    id: 2,
    category: "character",
    subCategory: "role",
    title: "THE ENG",
    text: "ห้ามพูดภาษาไทย! Speak English only (งู ๆ ปลา ๆ ก็ได้) หลุดไทยเมื่อไหร่ โดน!",
  },
  {
    id: 3,
    category: "character",
    subCategory: "role",
    title: "THE YES MAN",
    text: "ห้ามปฏิเสธ! ใครถามอะไรต้องตอบว่า ใช่ครับพี่ / ดีครับผม / เหมาะสมครับท่าน เท่านั้น",
  },
  {
    id: 4,
    category: "character",
    subCategory: "role",
    title: "THE HATER",
    text: "ห้ามหัวเราะ ห้ามยิ้ม ต้องทำหน้าตึงตลอด ใครทำให้คุณหลุดขำได้ คนนั้นรอด (คุณโดน)",
  },
  {
    id: 5,
    category: "character",
    subCategory: "role",
    title: "THE CAT",
    text: "ทุกประโยคที่พูดจบ ต้องลงท้ายด้วยเสียง เมี๊ยว~ ห้ามลืม!",
  },
  {
    id: 6,
    category: "character",
    subCategory: "role",
    title: "THE QUESTION",
    text: "ห้ามพูดประโยคบอกเล่า ต้องสื่อสารเป็นคำถามเท่านั้น",
  },
  {
    id: 7,
    category: "character",
    subCategory: "role",
    title: "THE ECHO",
    text: "ใครพูดประโยคสุดท้ายจบ คุณต้องพูดทวน 3 คำสุดท้ายซ้ำอีกที",
  },
  {
    id: 8,
    category: "character",
    subCategory: "role",
    title: "THE TWIN",
    text: "เลือกเพื่อน 1 คน คุณต้องทำท่าทางตามเพื่อนคนนั้นทุกอย่าง",
  },
  {
    id: 9,
    category: "character",
    subCategory: "role",
    title: "NO NAMES",
    text: "ห้ามเรียกชื่อจริงหรือชื่อเล่นเพื่อน ใช้คำสรรพนามตลก ๆ เท่านั้น",
  },
  {
    id: 10,
    category: "character",
    subCategory: "role",
    title: "THE POLITENESS",
    text: "ห้ามพูดคำหยาบ ต้องพูดจาสุภาพแบบนางสาวไทย",
  },
  {
    id: 11,
    category: "character",
    subCategory: "role",
    title: "NO PHONES",
    text: "ห้ามแตะมือถือเด็ดขาด ใครไลน์มา ห้ามตอบ ใครโทรมา ห้ามรับ",
  },
  {
    id: 12,
    category: "character",
    subCategory: "role",
    title: "THE STAND",
    text: "ห้ามนั่งเก้าอี้ ต้องยืนเล่นหรือนั่งพื้นเท่านั้น",
  },
  {
    id: 13,
    category: "character",
    subCategory: "role",
    title: "THE BUTLER",
    text: "ถ้าแก้วใครพร่องครึ่งหนึ่ง คุณต้องเติมให้ทันที ห้ามให้แก้วว่าง",
  },
  {
    id: 14,
    category: "character",
    subCategory: "role",
    title: "THE INFLU",
    text: "ก่อนดื่มทุกครั้ง ต้องทำท่า Boomerang ชนแก้ว แล้วพูดว่า Cheers!",
  },
  {
    id: 15,
    category: "character",
    subCategory: "role",
    title: "SECRET AGENT",
    text: "ห้ามสบตาใครตรง ๆ เวลาคุยต้องมองหูหรือเพดานเท่านั้น",
  },

  {
    id: 16,
    category: "question",
    subCategory: "deep",
    title: "Deep Talk",
    text: "ถ้าพรุ่งนี้โลกแตก อยากขอโทษใครในวงนี้มากที่สุด และเรื่องอะไร?",
  },
  {
    id: 17,
    category: "question",
    subCategory: "exposed",
    title: "Exposed",
    text: "เปิดรูปที่ 5 ในอัลบั้มมือถือให้ทุกคนดู ห้ามเปลี่ยน!",
  },
  {
    id: 18,
    category: "question",
    subCategory: "roast",
    title: "Roast",
    text: "ใครในวงนี้แต่งตัวไม่รอดที่สุดวันนี้? ชี้เลย",
  },
  {
    id: 19,
    category: "question",
    subCategory: "truth",
    title: "Truth",
    text: "เคยโกหกเพื่อนในวงนี้แล้วยังไม่ได้เฉลยไหม? เล่ามา",
  },
  {
    id: 20,
    category: "question",
    subCategory: "first-impression",
    title: "First Impression",
    text: "ความประทับใจแรกที่มีต่อคนทางขวามือ (ตรง ๆ)",
  },
  {
    id: 21,
    category: "question",
    subCategory: "dating",
    title: "Dating Life",
    text: "สเปคที่ชอบ vs ความเป็นจริงที่เจอ ต่างกันยังไง?",
  },
  {
    id: 22,
    category: "question",
    subCategory: "ghost",
    title: "Ghost",
    text: "เคยเทใครหรือโดนใครเทแบบงงที่สุดในชีวิต?",
  },
  {
    id: 23,
    category: "question",
    subCategory: "social",
    title: "Social",
    text: "ถ้าต้อง Unfriend เพื่อนในวงนี้ 1 คน จะเลือกใคร เพราะอะไร?",
  },
  {
    id: 24,
    category: "question",
    subCategory: "cringe",
    title: "Cringe",
    text: "เรื่องน่าอายที่สุดที่เคยทำตอนเมาคืออะไร?",
  },
  {
    id: 25,
    category: "question",
    subCategory: "rich",
    title: "Rich Kid",
    text: "ถ้าถูกหวยรางวัลที่ 1 จะพาเพื่อนในวงไปเลี้ยง หรือหนีไปคนเดียว?",
  },

  {
    id: 26,
    category: "minigame",
    subCategory: "category",
    title: "7-11",
    text: "ไล่ตอบของที่มีขายใน 7-11 ทีละคน ห้ามซ้ำ!",
  },
  {
    id: 27,
    category: "minigame",
    subCategory: "category",
    title: "T-POP / K-POP",
    text: "ไล่ตอบชื่อศิลปิน T-POP หรือ K-POP ทีละคน",
  },
  {
    id: 28,
    category: "minigame",
    subCategory: "category",
    title: "เมนูไข่",
    text: "ไล่ตอบเมนูที่มีไข่เป็นส่วนประกอบ ห้ามซ้ำ",
  },
  {
    id: 29,
    category: "minigame",
    subCategory: "category",
    title: "สระอา",
    text: "พูดคำ 2 พยางค์ที่มีสระอา (เช่น มาหา, ลาลา)",
  },
  {
    id: 30,
    category: "minigame",
    subCategory: "category",
    title: "ยี่ห้อรถ",
    text: "ไล่ตอบชื่อยี่ห้อรถยนต์ทีละคน ห้ามซ้ำ",
  },

  {
    id: 31,
    category: "minigame",
    subCategory: "reaction",
    title: "The Freeze",
    text: "ทุกคนหยุดนิ่ง ใครขยับก่อนแพ้",
  },
  {
    id: 32,
    category: "minigame",
    subCategory: "reaction",
    title: "High Pitch",
    text: "ร้องเพลงท่อนฮุคเสียงแหลม ใครเสียงปกติแพ้",
  },
  {
    id: 33,
    category: "minigame",
    subCategory: "reaction",
    title: "Counting",
    text: "นับ 1-10 พร้อมกัน ใครพูดชนกัน เริ่มใหม่",
  },
  {
    id: 34,
    category: "minigame",
    subCategory: "reaction",
    title: "Categories",
    text: "คนจั่วตั้งหมวด ไล่ตอบทีละคน",
  },
  {
    id: 35,
    category: "minigame",
    subCategory: "reaction",
    title: "Finger",
    text: "Never Have I Ever ใครนิ้วหมดก่อนแพ้",
  },
  {
    id: 36,
    category: "minigame",
    subCategory: "reaction",
    title: "Look Up",
    text: "นับ 1-3 แล้วมอง ถ้าสบตากันเอง โดนทั้งคู่",
  },
  {
    id: 37,
    category: "minigame",
    subCategory: "challenge",
    title: "The Painter",
    text: "วาดรูปบนหลังคนขวา ให้เขาทาย",
  },
  {
    id: 38,
    category: "minigame",
    subCategory: "challenge",
    title: "Rhyme",
    text: "พูดคำคล้องจองต่อกัน ใครคิดไม่ออกแพ้",
  },
  {
    id: 39,
    category: "minigame",
    subCategory: "challenge",
    title: "Highest",
    text: "ใครแบตมือถือเยอะที่สุดรอด น้อยสุดโดน",
  },
  {
    id: 40,
    category: "minigame",
    subCategory: "challenge",
    title: "Shortest",
    text: "ใครชื่อเล่นสั้นที่สุดชนะ ยาวสุดแพ้",
  },

  {
    id: 41,
    category: "normal",
    subCategory: "vote",
    title: "Vote",
    text: "โหวตคนเจ้าชู้เงียบที่สุด คนโดนโหวตมากสุดดื่ม",
  },
  {
    id: 42,
    category: "normal",
    subCategory: "vote",
    title: "Vote",
    text: "โหวตคนที่น่าจะครองโสดนานที่สุด",
  },
  {
    id: 43,
    category: "normal",
    subCategory: "vote",
    title: "Vote",
    text: "โหวตคนเมาแล้วรั่วที่สุด",
  },
  {
    id: 44,
    category: "normal",
    subCategory: "vote",
    title: "Vote",
    text: "โหวตคนที่ดูจะรวยทางลัดที่สุด",
  },
  {
    id: 45,
    category: "normal",
    subCategory: "vote",
    title: "Vote",
    text: "โหวตคนที่อยากให้มีความสุขที่สุดปีนี้ ดื่มฉลอง!",
  },

  {
    id: 46,
    category: "normal",
    subCategory: "break",
    title: "Free Time",
    text: "พักเบรก 5 นาที วางแก้ว เข้าห้องน้ำ เช็คไลน์ได้",
  },
  {
    id: 47,
    category: "normal",
    subCategory: "break",
    title: "Safe Zone",
    text: "เก็บไว้ปัดบทลงโทษได้ 1 ครั้ง",
  },
  {
    id: 48,
    category: "normal",
    subCategory: "break",
    title: "Harmony",
    text: "ชนแก้ว จิบพร้อมกันเพื่อมิตรภาพ",
  },

  {
    id: 49,
    category: "normal",
    subCategory: "action",
    title: "Drink",
    text: "ผู้จั่วดื่ม 1 shot",
  },
  {
    id: 50,
    category: "normal",
    subCategory: "action",
    title: "Drink",
    text: "ผู้จั่วดื่ม 1 shot แล้วเลือกเพื่อนดื่มด้วย 1 คน",
  },
  {
    id: 51,
    category: "normal",
    subCategory: "action",
    title: "Social",
    text: "ถ่ายรูปกลุ่ม ลง Story พร้อมแคปชั่น รักพวกมึงนะ",
  },
  {
    id: 52,
    category: "normal",
    subCategory: "action",
    title: "Duel",
    text: "เป่ายิ้งฉุบกับเพื่อน ใครแพ้ดื่ม",
  },
  {
    id: 53,
    category: "normal",
    subCategory: "action",
    title: "Command",
    text: "คนขวาสั่งให้คุณทำอะไรก็ได้ 1 อย่าง",
  },
  {
    id: 54,
    category: "normal",
    subCategory: "action",
    title: "Call",
    text: "โทรหาเพื่อนที่ไม่ได้มา บอกว่าคิดถึง",
  },
  {
    id: 55,
    category: "normal",
    subCategory: "action",
    title: "Switch",
    text: "เปลี่ยนที่นั่งทั้งวง",
  },
  {
    id: 56,
    category: "normal",
    subCategory: "action",
    title: "Feed",
    text: "ป้อนขนมให้เพื่อนซ้ายมือ 1 คำ",
  },
  {
    id: 57,
    category: "normal",
    subCategory: "action",
    title: "Dance",
    text: "เต้นหรือร้องเพลง 1 ท่อน",
  },
  {
    id: 58,
    category: "normal",
    subCategory: "action",
    title: "DJ",
    text: "เปิดเพลงที่ชอบให้เพื่อนฟังจนจบ",
  },
  {
    id: 59,
    category: "normal",
    subCategory: "action",
    title: "Respect",
    text: "ไหว้สวย ๆ รอบวง",
  },
  {
    id: 60,
    category: "normal",
    subCategory: "action",
    title: "Stare",
    text: "จ้องตาเพื่อน 10 วิ ใครขำแพ้",
  },
  {
    id: 61,
    category: "normal",
    subCategory: "action",
    title: "Joke",
    text: "เล่าเรื่องตลก ถ้าไม่มีใครขำ คุณดื่มเอง",
  },
  {
    id: 62,
    category: "normal",
    subCategory: "action",
    title: "Selfie",
    text: "เซลฟี่หน้าเผลอ ส่งเข้าไลน์กลุ่ม",
  },
  {
    id: 63,
    category: "normal",
    subCategory: "action",
    title: "Water",
    text: "ดื่มน้ำเปล่า 1 แก้วเต็ม",
  },
  {
    id: 64,
    category: "normal",
    subCategory: "action",
    title: "Buddy",
    text: "จับคู่ Buddy ดื่มพร้อมกันจนจบเกม",
  },
  {
    id: 65,
    category: "normal",
    subCategory: "action",
    title: "Drama",
    text: "แกล้งทำเป็นเมา พูดไม่รู้เรื่อง 1 นาที",
  },
  {
    id: 66,
    category: "normal",
    subCategory: "action",
    title: "Review",
    text: "รีวิวเพื่อนข้าง ๆ เหมือนรีวิวสินค้า",
  },
  {
    id: 67,
    category: "normal",
    subCategory: "action",
    title: "Sexy",
    text: "ทำหน้าที่คิดว่าเซ็กซี่ที่สุด",
  },
  {
    id: 68,
    category: "normal",
    subCategory: "action",
    title: "Self Love",
    text: "บอกข้อดีของตัวเอง 3 ข้อ",
  },

  {
    id: 69,
    category: "normal",
    subCategory: "position",
    title: "Left",
    text: "คนทางซ้ายมือผู้จั่ว โดน!",
  },
  {
    id: 70,
    category: "normal",
    subCategory: "position",
    title: "Right",
    text: "คนทางขวามือผู้จั่ว โดน!",
  },
  {
    id: 71,
    category: "normal",
    subCategory: "position",
    title: "Opposite",
    text: "คนนั่งตรงข้ามผู้จั่ว โดน!",
  },
  {
    id: 72,
    category: "normal",
    subCategory: "position",
    title: "Left 2",
    text: "คนที่ 2 ทางซ้ายผู้จั่ว โดน!",
  },
  {
    id: 73,
    category: "normal",
    subCategory: "position",
    title: "Right 2",
    text: "คนที่ 2 ทางขวาผู้จั่ว โดน!",
  },
  {
    id: 74,
    category: "normal",
    subCategory: "position",
    title: "Triple",
    text: "ผู้จั่วและคนซ้ายขวา โดนพร้อมกัน",
  },
  {
    id: 75,
    category: "normal",
    subCategory: "position",
    title: "All Except",
    text: "ทุกคนยกเว้นผู้จั่ว โดน!",
  },
  {
    id: 76,
    category: "normal",
    subCategory: "position",
    title: "Point Left",
    text: "ชี้ซ้าย ใครโดนนิ้วชี้ก่อน โดน!",
  },
  {
    id: 77,
    category: "normal",
    subCategory: "position",
    title: "Point Right",
    text: "ชี้ขวา ใครโดนนิ้วชี้ก่อน โดน!",
  },
  {
    id: 78,
    category: "normal",
    subCategory: "position",
    title: "Door",
    text: "คนนั่งใกล้ประตูที่สุด โดน!",
  },

  {
    id: 79,
    category: "normal",
    subCategory: "attribute",
    title: "Glasses",
    text: "ใครใส่แว่นอยู่ตอนนี้ โดน!",
  },
  {
    id: 80,
    category: "normal",
    subCategory: "attribute",
    title: "Monotone",
    text: "ใครใส่เสื้อขาวหรือดำ โดน!",
  },
  {
    id: 81,
    category: "normal",
    subCategory: "attribute",
    title: "Tall",
    text: "ใครตัวสูงที่สุด โดน!",
  },
  {
    id: 82,
    category: "normal",
    subCategory: "attribute",
    title: "Small",
    text: "ใครตัวเล็กที่สุด โดน!",
  },
  {
    id: 83,
    category: "normal",
    subCategory: "attribute",
    title: "Long Hair",
    text: "ใครผมยาวกว่าบ่า โดน!",
  },
  {
    id: 84,
    category: "normal",
    subCategory: "attribute",
    title: "Short Hair",
    text: "ใครผมสั้น โดน!",
  },
  {
    id: 85,
    category: "normal",
    subCategory: "attribute",
    title: "Month คม",
    text: "ใครเกิดเดือนลงท้าย คม โดน!",
  },
  {
    id: 86,
    category: "normal",
    subCategory: "attribute",
    title: "Month ยน",
    text: "ใครเกิดเดือนลงท้าย ยน โดน!",
  },
  {
    id: 87,
    category: "normal",
    subCategory: "attribute",
    title: "February",
    text: "ใครเกิดกุมภาพันธ์ โดน! ถ้าไม่มี รอดหมด",
  },
  {
    id: 88,
    category: "normal",
    subCategory: "attribute",
    title: "One Syllable",
    text: "ใครชื่อเล่นพยางค์เดียว โดน!",
  },
  {
    id: 89,
    category: "normal",
    subCategory: "attribute",
    title: "Letter น",
    text: "ใครชื่อจริงมีตัวอักษร น โดน!",
  },
  {
    id: 90,
    category: "normal",
    subCategory: "attribute",
    title: "Oldest",
    text: "ใครอายุมากที่สุด โดน!",
  },
  {
    id: 91,
    category: "normal",
    subCategory: "attribute",
    title: "Youngest",
    text: "ใครอายุน้อยที่สุด โดน!",
  },
  {
    id: 92,
    category: "normal",
    subCategory: "attribute",
    title: "No Socks",
    text: "ใครไม่ใส่ถุงเท้า โดน!",
  },
  {
    id: 93,
    category: "normal",
    subCategory: "attribute",
    title: "Watch",
    text: "ใครใส่นาฬิกาอยู่ โดน!",
  },

  {
    id: 94,
    category: "normal",
    subCategory: "status",
    title: "Single",
    text: "ใครโสด โดน!",
  },
  {
    id: 95,
    category: "normal",
    subCategory: "status",
    title: "In Love",
    text: "ใครมีแฟนหรือคนคุย โดน!",
  },
  {
    id: 96,
    category: "normal",
    subCategory: "status",
    title: "Phone Addict",
    text: "ใครเล่นมือถือบ่อยสุดใน 10 นาทีที่ผ่านมา โดน!",
  },
  {
    id: 97,
    category: "normal",
    subCategory: "status",
    title: "Red Face",
    text: "ใครหน้าแดงที่สุดตอนนี้ โดน!",
  },
  {
    id: 98,
    category: "normal",
    subCategory: "status",
    title: "Influencer",
    text: "ใคร IG Follower เยอะที่สุด โดน!",
  },
  {
    id: 99,
    category: "normal",
    subCategory: "status",
    title: "Cashless",
    text: "ใครพกเงินสดน้อยที่สุด โดน!",
  },
  {
    id: 100,
    category: "normal",
    subCategory: "status",
    title: "Jackpot",
    text: "คนจั่วเลือกใครก็ได้ 1 คน ให้รับบทลงโทษแทน หรือรับเอง",
  },
];
